# Generated by Django 4.1.7 on 2023-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminuser',
        ),
    ]
