# Generated by Django 4.1.7 on 2023-02-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminuser',
        ),
    ]
