# Generated by Django 3.2.12 on 2023-01-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecom',
        ),
    ]
