# Generated by Django 3.2.12 on 2023-01-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
