# Generated by Django 3.2.12 on 2023-01-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_addproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='total',
        ),
    ]
