# Generated by Django 3.2.12 on 2023-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
