# Generated by Django 3.2.12 on 2023-01-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orderplaced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
