# Generated by Django 4.1.6 on 2023-02-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Addproduct',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
