# Generated by Django 4.1.6 on 2023-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_addproduct_category_customer_subcategory_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
