# Generated by Django 4.1.6 on 2023-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('category_id', models.CharField(max_length=200)),
                ('Subcategory_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('product_qty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
