# Generated by Django 4.1.6 on 2023-02-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
