# Generated by Django 4.1.7 on 2023-02-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
