# Generated by Django 4.1.7 on 2023-02-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
